config/routes.rb
Omrailsss::Application.routes.draw do 
  resources :pins

  devise_for :users
  get 'about' => 'pages#about'
  root :to => 'pages#home'

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	attr_accessible :description, :image


	validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 5.megabytes }


	belongs_to :user
	has_attached_file :image, styles: { medium: "320X240>"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         #:recoverable, 
         :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :provider, :uid, :as => [:default, :admin]

  has_many :pins, :dependent => :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  def create
    @pin = current_user.pins.create(pin_params)

    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /pins/1
  def update
    if @pin.update_attributes(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /pins/1
  def destroy
    @pin.destroy
    redirect_to pins_url, notice: 'Pin was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = current_user.pins.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb

	<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "One Month Rails",root_path, class: "brand" %>
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	    <ul class="nav">
	        	<li><%= link_to "Home",root_path %></li>
		        <li><%= link_to "About US",about_path %></li>
		        <li><%= link_to "Essayest",about_path %></li>
	        </ul>
	        <ul class="nav pull-right">
            <% if user_signed_in? %>
            <li><%= link_to "Edit Profile",edit_user_registration_path%></li>
            <li><%= link_to "Logout",destroy_user_session_path, method: :delete %></li>
            <% else %>
	        	<li><%= link_to "Login",new_user_session_path %></li>
	        <% end %>
          </ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>One Month Rails</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
    <%= render 'layouts/header' %>
	    	<div class="container">
	            <% flash.each do |name, msg| %>
	                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
	

	</body>
</html>

app/views/pages/about.html.erb

<h1>About</h1>
<p>
	 <%= link_to "One Month Rails","http://onemonthrails.com" %>
	 is a project to teach <%= link_to "Ruby on Rails","http://onemonthrails.com" %>in one month,this is the sample application
<p>


app/views/pages/home.html.erb
<% if user_signed_in? %>
  <h1>Welcome to One month Rails! You have logged in</h1>
 <% else %>
<div class="hero-unit">
	<h1>Welcome to One month Rails!</h1>
	<p>
		you have found the home page for the
		<%= link_to "One Month Rails","http://onemonthrails.com" %>
		application.
	</p>

	</p>
	    <%= link_to "Sign Up now",new_user_registration_path, class: "btn btn-success btn-large" %>

	</p>
</div>
<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <%= f.input :image, label: "Upload an Image" %>
  <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<tr>
	   <td><%= image_tag pin.image(:medium) %></td>
	   <td><%= pin.description %></td>
		 <td><%= link_to 'Show', pin %></td>
		 <% if current_user == pin.user%>
			 <td><%= link_to 'Edit', edit_pin_path(pin) %></td>
	     <td><%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	    <% end %>
 </tr>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<h1>Listing pins</h1>

<table class= "table table-striped">
  <thead>
      <tr>
        <th>Image</th>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
  </thead>

  <tbody>
   <%= render @pins %>
  </tbody>
</table>

<br>

<%= link_to 'New Pin', new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class ="well">
			<%= image_tag @pin.image %>
			<p>
			  <strong>Description:</strong>
			  <%= @pin.description %>
			</p>

        <% if current_user == @pin.user%>
					<%= link_to 'Edit', edit_pin_path(@pin) %> |
	    		<%= link_to 'Back', pins_path %>  
    		<% end %>
	  </div>
	</div>
</div>